# Build stage
FROM golang:1.23.3-alpine3.20 AS builder

# 设置必要的环境变量
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 
    # \GOPROXY=https://goproxy.cn,direct

# 设置工作目录
WORKDIR /build

# 安装基本依赖
# RUN apk add --no-cache git make

# 复制 go.mod 和 go.sum
COPY go.mod go.sum ./
# RUN go env -w GOPROXY="https://goproxy.cn"
# 下载依赖
RUN go mod download

# 复制源代码
COPY . .

# 编译 (注意这里改为 cmd/server 路径)
RUN go build -o cybernity ./cmd/server

# Final stage
FROM alpine:3.20

WORKDIR /app

# 设置时区
ENV TZ=UTC
# 从 builder 阶段复制编译好的二进制文件
COPY --from=builder /build/cybernity .

# 设置启动命令
ENTRYPOINT ["/app/cybernity"]

